blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/skanda-observeai/zeus-sdk-py/discussions
    about: Ask questions and discuss with the community
  - name: Documentation
    url: https://github.com/skanda-observeai/zeus-sdk-py#readme
    about: Check the documentation for help
